name: GitHub Actions Test
run-name: ${{github.actor}} is testing ExcelJS package
on:
  push:
    branches: [main, bhavya]
  pull_request:
    branches: [main, bhavya]
    types:
      - closed # trigger on merge
jobs:
  Test-ExcelJS:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ¤– This job was automatically triggered by a ${{github.event_name}} event."
      - run: echo "ğŸ–¥ï¸ This job is now running on a ${{runner.os}} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{github.ref}} and your repository is ${{github.repository}}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ§¬ The ${{github.repository}} repository has been cloned to the runner."
      - run: echo "ğŸ§ª The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: ls ${{github.workspace}}
      - name: Clean Install npm with dependencies
        run: npm ci
      - name: Test excelDemo.js file
        run: node excelDemo.js
      - run: echo "ğŸ‰ This job's status is ${{job.status}}."
